spring:
  application:
    name: ye-ai-code-mother-backend
  profiles:
    active: local

  # mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ye_ai_code_mother
    username: root
    password: 123456

server:
  port: 8123
  servlet:
    context-path: /api
# springdoc-openapi
springdoc:
  group-configs:
    - group: 'default'
      packages-to-scan: com.ye.yeaicodemother.controller
# knife4j
knife4j:
  enable: true
  setting:
    language: zh_cn

